# Generated by Django 3.2.7 on 2021-10-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211001_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='Branche_Name',
        ),
    ]
