# Generated by Django 3.2.7 on 2021-10-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userbankaccount_branche_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankBranche',
        ),
    ]
