# Generated by Django 3.2.7 on 2021-10-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_bankbranche'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('City', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
