# Generated by Django 3.2.7 on 2021-10-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankbranche'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='Branche_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.bankbranche'),
            preserve_default=False,
        ),
    ]
