# Generated by Django 3.2.7 on 2021-10-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userbankaccount_branche_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='Branche_Name',
            new_name='branche_name',
        ),
    ]
