# Generated by Django 3.2.7 on 2021-10-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_loan_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbranche',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_user', to='accounts.user'),
            preserve_default=False,
        ),
    ]
